#IMPORTANT !! Enable the player color code.
#Enabling the color code will create a separate scoreboard for each player, thus BREAKING THE VANILLA SCOREBOARD
#Only enable this if you are not using any other scoreboard plugin
EnablePlayerColorCode: false

#The amount of money a player starts with (only if no economy plugin is linked to the server)
StartingMoney: 100

#The cost of creating a town
CostOfCreatingTown: 1000

#The cost of a town claim
CostOfChunk: 0
#The cost of a region claim
CostOfRegionChunk: 5

#The cost of a town upkeeping 10 chunks
ChunkUpkeepCost: 0

#Allow non-adjacent chunks to be claimed
AllowNonAdjacentChunks: false

#Notify if a player from an enemy town enters his town
notifyEnemyTownEnter: true


#Town Levels (town level cost are in the townLevelUpRequirement.yml file)
TownMaxLevel: 10


#The cost of creating a Region
regionCost: 7500


#The max size of names
TownNameSize: 40
RankNameSize: 25
TownDescSize: 50
RegionNameSize: 40
RegionDescSize: 50



#Rare items, used for the economy when no economy plugin is added to the server
##You can disable rare Item dropping with RAREITEMSPAWN: FALSE
RARE_RESOURCES_SPAWN: true

#Allow players to sell rare ressources directly through /tan sell
#If set to false, players can still sell to villagers.
AllowSellRareRessourcesByCommand: true

#The stat of getting a rare Stone, used to get money
# (20 = 20% drop chance when breaking this block without a silk touch pick)
rareStone:
  GOLD_ORE: 35
  DEEPSLATE_GOLD_ORE: 35
  DIAMOND_ORE: 30
  DEEPSLATE_DIAMOND_ORE: 30
  EMERALD_ORE: 50
  DEEPSLATE_EMERALD_ORE: 50
  REDSTONE_ORE: 15
  DEEPSLATE_REDSTONE_ORE: 15
  LAPIS_ORE: 25
  DEEPSLATE_LAPIS_ORE: 25

rareStoneValue: 5


#The stat of getting rare Wood, used to get money
rareWood:
  ACACIA_LOG: 3
  BIRCH_LOG: 3
  DARK_OAK_LOG: 3
  JUNGLE_LOG: 3
  OAK_LOG: 3
  SPRUCE_LOG: 3

rareWoodValue: 3

#The stat of getting rare Crops, used to get money
rareCrops:
  WHEAT: 4
  CARROTS: 3
  POTATOES: 3
  BEETROOTS: 3
  PUMPKIN: 0
  MELON: 0

rareCropsValue: 3


#The stat of getting souls, used to get money. You can use any entity type
rareSoul:
  ZOMBIE: 5
  CREEPER: 15
  SKELETON: 5
  SPIDER: 5
  ENDERMAN: 100
  WITCH: 10
  PIGLIN: 5
  PIGLIN_BRUTE: 5
  ZOMBIFIED_PIGLIN: 0
  HUSK: 15
  STRAY: 15

  CAVE_SPIDER: 5
  DROWNED: 5
  BLAZE: 5
  GHAST: 75

rareSoulValue: 2

##
#Cost of renaming a town:
ChangeTownNameCost: 100

#Duration of a war in minutes
WarDurationTime: 60

##Cross server config
#Enable cross server (will require a MySQL database)
EnableCrossServer: false
SQL:
  #ip of the mysql server
  address: jdbc:mysql://localhost:3306/minecraft
  #username of the database
  username: root
  #password of the database
  password: password

#Remove all villager interactions except the one from the plugin
removeAllVillagerInteractions: false

##Clearing RAM memory
#Time before tax history is cleared in days (can be set to 0 to disable the clearing)
TimeBeforeClearingTaxHistory: 30
#Time before chunk history is cleared in days (can be set to 0 to disable the clearing)
TimeBeforeClearingChunkHistory: 30
#Number of donation before it is cleared (can be set to 0 to disable the clearing)
NumberOfDonationBeforeClearing: 100
#Number of Miscellaneous purchase before it is cleared (can be set to 0 to disable the clearing)
NumberOfMiscPurchaseBeforeClearing: 100


#Write the type of mobs you want a town to be able to cancel the spawn of.
#If you want the removal option to be free, write 0, else write the cost of the removal
#If you do not need a mob to be removed, do not write it
CancelMobSpawnInTown:
  GLOW_SQUID: 0
  SQUID: 0
  BAT: 50
  SLIME: 50
  CREEPER: 0
  SKELETON: 0
  SPIDER: 0
  ZOMBIE: 0
  ENDERMAN: 0

##Teleportation
#Time before a teleportation (in seconds). 0 or negative value will result in an instant teleportation
timeBeforeTeleport: 5
#Cancel teleportation if player move
cancelTeleportOnMove: true
#Cancel teleportation if player take damage
cancelTeleportOnDamage: true

#Archive major event into a txt file
archiveHistory: true

#Show message when tax in the console
showTaxInConsole: true

#Time of the day when taxes are collected
taxHourTime: 0 #0-23
taxMinuteTime: 0 #0-59
