#  _____                            ___       _   _       _   _
# |_   ______      ___ __  ___     ( _ )     | \ | | __ _| |_(_) ___  _ __  ___
#   | |/ _ \ \ /\ / | '_ \/ __|    / _ \/\   |  \| |/ _` | __| |/ _ \| '_ \/ __|
#   | | (_) \ V  V /| | | \__ \   | (_>  <   | |\  | (_| | |_| | (_) | | | \__ \
#   |_|\___/ \_/\_/ |_| |_|___/    \___/\/   |_| \_|\__,_|\__|_|\___/|_| |_|___/
#


########################
##      General       ##
########################

#Allow name duplication (for ranks, towns, regions and kingdoms)
AllowNameDuplication: true

#Remove all villager interactions except the one from the plugin (usefull to prevent duplication of items)
removeAllVillagerInteractions: false

#Time of the day when taxes are collected (default is midnight)
taxHourTime: 0 #0-23
taxMinuteTime: 0 #0-59

########################
##      Players       ##
########################

#IMPORTANT !! Enable the player color code.
#Enabling the color code will create a separate scoreboard for each player, thus BREAKING THE VANILLA SCOREBOARD
#Only enable this if you are not using any other scoreboard plugin
EnablePlayerColorCode: false

#If the player color code is enable, you can add a 3 character prefix to the player name from their town
EnablePlayerPrefix: false

#Enable prefix for town
EnableTownPrefix: true

#Enable the version check
CheckForUpdate: true

#If prefix enabled:
##Prefix Size (recommended 3)
prefixSize: 3

########################
##      Kingdoms      ##
########################

#Enable Kingdoms
EnableKingdom: true

#The amount of money a player starts with (only if no economy plugin is linked to the server)
StartingMoney: 100

########################
##      Kingdoms      ##
########################

#Enable Region (will automatically disable Kingdoms)
EnableRegion: true

#The cost of creating a Region
regionCost: 7500

#The max size of names
TownNameSize: 45
TownDescSize: 55

#Cost of renaming a region:
ChangeRegionNameCost: 100

#The cost of a region claim
CostOfRegionChunk: 5

#The cost 10 region chunks upkeep
RegionChunkUpkeepCost: 0

#Allow non-adjacent chunks to be claimed
RegionAllowNonAdjacentChunks: false

#Notify if a player from an enemy territory enters
notifyEnemyEnterRegion: true

########################
##       Towns        ##
########################

#The cost of creating a town
townCost: 1000

#The max size of names
RegionNameSize: 45
RegionDescSize: 55

#Cost of renaming a town:
ChangeTownNameCost: 100

#The cost of a town claim
CostOfTownChunk: 0

#The cost 10 town chunks upkeep
TownChunkUpkeepCost: 0

#Allow non-adjacent chunks to be claimed
TownAllowNonAdjacentChunks: false

#Notify if a player from an enemy town enters
notifyEnemyEnterTown: true

#Town Levels (town level cost are in the townLevelUpRequirement.yml file)
TownMaxLevel: 10


########################
##     Properties     ##
########################

#Define the maximum range at which a player can be from a town spawn to be considered in the town
maxPropertyMargin: 3
#When a player rent a property, make the player pay the rent one extra time at start
payRentAtStart: true

#The max size of names
PropertyNameSize: 16
PropertyDescSize: 40

#Max size of a property (length x width x height)
MaxPropertySize: 50000


########################
##       Ranks        ##
########################

#The max number of rank a town can create
townMaxRank: 9

RankNameSize: 25

########################
##        Wars        ##
########################

#Enable war
EnableWar: true

#Duration of an attack in minutes
WarDurationTime: 60

#Minimum time before starting an attack (in minutes)
MinimumTimeBeforeAttack: 1440 #24 hours

#Maximum time before starting an attack (in minutes)
MaximumTimeBeforeAttack: 4320 #72 hours


########################
##  RARES RESSOURCES  ##
########################

#ENABLE RARE RESSOURCES SPAWN
RARE_RESOURCES_SPAWN: true

#Allow players to sell rare ressources directly through /tan sell
AllowSellRareRessourcesByCommand: true

#The probability of obtaining a rare Stone. (trigger by breaking a block)
# (20 = 20% drop chance when breaking this block without a silk touch pick)
rareStone:
  GOLD_ORE: 35
  DEEPSLATE_GOLD_ORE: 35
  DIAMOND_ORE: 30
  DEEPSLATE_DIAMOND_ORE: 30
  EMERALD_ORE: 50
  DEEPSLATE_EMERALD_ORE: 50
  REDSTONE_ORE: 15
  DEEPSLATE_REDSTONE_ORE: 15
  LAPIS_ORE: 25
  DEEPSLATE_LAPIS_ORE: 25

rareStoneValue: 5


#The probability of obtaining rare Wood. (trigger when breaking a block)
rareWood:
  ACACIA_LOG: 3
  BIRCH_LOG: 3
  DARK_OAK_LOG: 3
  JUNGLE_LOG: 3
  OAK_LOG: 3
  SPRUCE_LOG: 3

rareWoodValue: 3

#The probability of obtaining rare Crops. (trigger when breaking a FULLY GROWN crop only)
rareCrops:
  WHEAT: 4
  CARROTS: 3
  POTATOES: 3
  BEETROOTS: 3
  PUMPKIN: 0
  MELON: 0

rareCropsValue: 3


#The probability of obtaining souls. (trigger when killing a mob)
rareSoul:
  ZOMBIE: 5
  CREEPER: 15
  SKELETON: 5
  SPIDER: 5
  ENDERMAN: 100
  WITCH: 10
  PIGLIN: 5
  PIGLIN_BRUTE: 5
  ZOMBIFIED_PIGLIN: 0
  HUSK: 15
  STRAY: 15

  CAVE_SPIDER: 5
  DROWNED: 5
  BLAZE: 5
  GHAST: 75

rareSoulValue: 15

#The probability of obtaining rare fishes. (trigger when fishing. hook must be in water)

rareFish:
  SALMON: 4
  COD: 4
  PUFFERFISH: 8
  TROPICAL_FISH: 12

rareFishValue: 20

########################
##    TELEPORTATION   ##
########################

##Teleportation
#Time before a teleportation (in seconds). 0 or negative value will result in an instant teleportation
timeBeforeTeleport: 5

#Cancel teleportation if player move head
cancelTeleportOnMoveHead: false

#Cancel teleportation if player move position
cancelTeleportOnMovePosition: true

#Cancel teleportation if player take damage
cancelTeleportOnDamage: true


########################
##      Landmarks     ##
########################

#Max size of a landmark name
landmarkNameMaxSize: 25


########################
##       Sounds       ##
########################
enableSounds: true
#1 - Sound name
#2 - Volume
#3 - Pitch
sounds:
  LEVEL_UP: [ "ENTITY_PLAYER_LEVELUP", "1", "1" ]
  MINOR_LEVEL_UP: [ "ENTITY_PLAYER_LEVELUP", "1", "6" ]
  ADD: [ "BLOCK_NOTE_BLOCK_HAT", "1", "8" ]
  REMOVE: [ "BLOCK_NOTE_BLOCK_HAT", "1", "6" ]
  NOT_ALLOWED: [ "BLOCK_NOTE_BLOCK_HAT", "1", "2" ]
  WAR: [ "ITEM_GOAT_HORN_SOUND_0", "1", "1" ]
  GOOD: [ "ENTITY_EXPERIENCE_ORB_PICKUP", "1", "1.7" ]
  MINOR_GOOD: [ "BLOCK_AMETHYST_BLOCK_BREAK", "1", "1" ]
  BAD: [ "BLOCK_BELL_USE", "1", "1.5" ]
  MINOR_BAD: [ "ENTITY_SLIME_ATTACK", "1", "6" ]







##Cross server config (DISABLED SINCE 0.3.0)
#Enable cross server (will require a MySQL database)
EnableCrossServer: false
SQL:
  #ip of the mysql server
  address: jdbc:mysql://localhost:3306/minecraft
  #username of the database
  username: root
  #password of the database
  password: password


########################
##       Storage      ##
########################

#Archive major event into a txt file
archiveHistory: true


#Time before tax history is cleared in days (can be set to 0 to disable the clearing)
TimeBeforeClearingTaxHistory: 30
#Time before chunk history is cleared in days (can be set to 0 to disable the clearing)
TimeBeforeClearingChunkHistory: 30
#Number of donation before it is cleared (can be set to 0 to disable the clearing)
NumberOfDonationBeforeClearing: 100
#Number of Miscellaneous purchase before it is cleared (can be set to 0 to disable the clearing)
NumberOfMiscPurchaseBeforeClearing: 100


#Write the type of mobs you want a town to be able to cancel the spawn of.
#If you want the removal option to be free, write 0, else write the cost of the removal
#If you do not want some mobs to be removed, write -1 or any other negative number
CancelMobSpawnInTown:
  AXOLOTL: 0
  BAT: 50
  BEE: 0
  BLAZE: 0
  CAMEL: 0
  CAT: 0
  CAVE_SPIDER: 500
  CHICKEN: 0
  COD: 0
  COW: 0
  CREEPER: 1000
  DOLPHIN: 0
  DONKEY: 0
  DROWNED: 500
  ENDERMAN: 1000
  ENDERMITE: 0
  EVOKER: 0
  FOX: 0
  FROG: 0
  GHAST: 1000
  GLOW_SQUID: 0
  GOAT: 0
  GUARDIAN: 0
  HOGLIN: 0
  HORSE: 0
  HUSK: 500
  IRON_GOLEM: 0
  LLAMA: 0
  MAGMA_CUBE: 0
  MOOSHROOM: 0
  MULE: 0
  OCELOT: 0
  PANDA: 0
  PARROT: 0
  PHANTOM: 0
  PIG: 0
  PIGLIN: 0
  PIGLIN_BRUTE: 0
  PILLAGER: 0
  POLAR_BEAR: 0
  PUFFERFISH: 0
  RABBIT: 0
  RAVAGER: 0
  SALMON: 0
  SHEEP: 0
  SHULKER: 0
  SILVERFISH: 0
  SKELETON: 1000
  SKELETON_HORSE: 0
  SLIME: 0
  SNOWMAN: 0
  SPIDER: 500
  SQUID: 0
  STRAY: 500
  STRIDER: 0
  TRADER_LLAMA: 0
  TROPICAL_FISH: 0
  TURTLE: 0
  VEX: 0
  VILLAGER: 0
  VINDICATOR: 0
  WANDERING_TRADER: 0
  WITCH: 0
  WITHER: 0
  WITHER_SKELETON: 0
  WOLF: 0
  ZOGLIN: 0
  ZOMBIE: 1000
  ZOMBIE_HORSE: 0
  ZOMBIE_VILLAGER: 0







