#IMPORTANT !! Enable the player color code.
#Enabling the color code will create a separate scoreboard for each player, thus BREAKING THE VANILLA SCOREBOARD
#Only enable this if you are not using any other scoreboard plugin
EnablePlayerColorCode: false

#The amount of money a player starts with (only if no economy plugin is linked to the server)
StartingMoney: 100

#The cost of creating a town
CostOfCreatingTown: 1000

#The cost of a chunk to claim
CostOfChunk: 0

#The cost of upkeeping 10 chunks
ChunkUpkeepCost: 0

#Allow non-adjacent chunks to be claimed
AllowNonAdjacentChunks: false

#Notify if a player from an enemy town enters his town
notifyEnemyTownEnter: true


#Town Levels (town level cost are in the townLevelUpRequirement.yml file)
TownMaxLevel: 10
TownMaxMemberLevel: 10
TownMaxChunkLevel: 10

TownStartingMembersCap: 5
UpgradeMembers: 3

TownStartingChunksCap: 50
TownUpgradeChunk: 25


#The max size of names

TownNameSize: 40
RankNameSize: 25
TownDescSize: 50


#Rare items, used for the economy when no economy plugin is added to the server
##You can disable rare Item dropping with RAREITEMSPAWN: FALSE
RARE_RESOURCES_SPAWN: true

#The stat of getting a rare Stone, used to get money
# (20 = 20% drop chance when breaking this block without a silk touch pick)
rareStone:
  GOLD_ORE: 35
  DEEPSLATE_GOLD_ORE: 35
  DIAMOND_ORE: 30
  DEEPSLATE_DIAMOND_ORE: 30
  EMERALD_ORE: 50
  DEEPSLATE_EMERALD_ORE: 50
  REDSTONE_ORE: 15
  DEEPSLATE_REDSTONE_ORE: 15
  LAPIS_ORE: 25
  DEEPSLATE_LAPIS_ORE: 25

rareStoneValue: 5


#The stat of getting rare Wood, used to get money
rareWood:
  ACACIA_LOG: 3
  BIRCH_LOG: 3
  DARK_OAK_LOG: 3
  JUNGLE_LOG: 3
  OAK_LOG: 3
  SPRUCE_LOG: 3

rareWoodValue: 3

#The stat of getting rare Crops, used to get money
rareCrops:
  WHEAT: 4
  CARROTS: 3
  POTATOES: 3
  BEETROOTS: 3
  PUMPKIN: 0
  MELON: 0

rareCropsValue: 3

##
#Cost of renaming a town:
ChangeTownNameCost: 100

#Duration of a war in minutes
WarDurationTime: 60

#Allow color coding in username. May cause problem if mixed with other plugins
AllowColorInUsername: true

##Corss server config
#Enable cross server (will require a MySQL database)
EnableCrossServer: false

SQL:
  #ip of the mysql server
  address: jdbc:mysql://localhost:3306/minecraft
  #username of the database
  username: root
  #password of the database
  password: password
