
#The language of the plugin
##Language available: en, fr.
##<languageCode>.yml
Language: en.yml

#The cost of a chunk
CostOfChunk: 0

#The cost of creating a town
CostOfCreatingTown: 1000

#Town Levels (town level cost are in the townLevelUpRequirement.yml file)
TownMaxLevel: 10

TownStartingMembersCap: 5
UpgradeMembers: 3

TownStartingChunksCap: 50
TownUpgradeChunk: 25


#The stat of getting a rare Stone, used to get money
# (20 = 20% drop chance when breaking this block without a silk touch pick)
rareStone:
  GOLD_ORE: 30
  DEEPSLATE_GOLD_ORE: 30
  DIAMOND_ORE: 50
  DEEPSLATE_DIAMOND_ORE: 50

rareStoneValue: 5


#The stat of getting rare Wood, used to get money
rareWood:
  ACACIA_LOG: 3
  BIRCH_LOG: 3
  DARK_OAK_LOG: 3
  JUNGLE_LOG: 3
  OAK_LOG: 3
  SPRUCE_LOG: 3

rareWoodValue: 3

#The stat of getting rare Crops, used to get money
rareCrops:
  WHEAT: 5

rareCropsValue: 3