name: TownsAndNations
version: '${version}'
main: org.tan.TownsAndNations.TownsAndNations
api-version: 1.19
authors: [ Leralix ]
softdepend: [Vault]
description: A town plugin with rp tools
commands:
  tan:
    description: base command of Town and Nation
    permission: townandnation.base
    usage: /<command>
  tandebug:
    description: debug command of Town and Nation
    permission: townandnation.admin
    usage: /<command> 


