name: TownsAndNations
version: '${version}'
main: org.tan.towns_and_nations.TownsAndNations
api-version: 1.19
authors: [ Leralix ]
description: My first big plugin
commands:
  tan:
    description: base command of Town and Nation
    permission: townandnation.base
    usage: /<command>
  tandebug:
    description: debug command of Town and Nation
    permission: townandnation.admin
    usage: /<command> 

depend: [LuckPerms, ProtocolLib]

